--- #YAML:1.0
name:               Net-DRI
version:            0.96_02
abstract:           Interface to Domain Name Registries/Registrars/Resellers
author:
    - Patrick Mevzek <netdri@dotandco.com>
license:            gpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::LongString:  0
    Test::More:        0
requires:
    Class::Accessor:      0
    Class::Accessor::Chained:  0
    DateTime:             0
    DateTime::Duration:   0
    DateTime::Format::ISO8601:  0.06
    DateTime::Format::Strptime:  0
    DateTime::TimeZone:   0
    Email::Valid:         0
    IO::Socket::SSL:      0.90
    perl:                 5.008000
    Test::LongString:     0
    Test::More:           0
    UNIVERSAL::require:   0
    XML::LibXML:          1.61
resources:
    bugtracker:  nntp://news.dotandco.net/dotandco.discuss
    homepage:    http://www.dotandco.com/services/software/Net-DRI/index.en
    license:     http://www.dotandco.com/services/software/Net-DRI/index.en#license
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
keywords:
    - DNS
    - EPP
    - RRP
    - DAS
    - ENUM
    - IRIS
    - DCHK
    - Whois
    - gTLD
    - ccTLD
    - domain
optional_features:
    digest:
        description:  Support of MD5 digest for OpenSRS
        requires:
            Digest::MD5:  0
    email:
        description:  Support of email handling for .FR
        requires:
            MIME::Entity:  0
            Net::SMTP:     0
    http:
        description:  Support of HTTP(S) transport for OpenSRS, .IT and .PL
        requires:
            HTTP::Request:   0
            LWP::UserAgent:  6.02
    iris:
        description:  Support of IRIS inflation/deflation & DNS SRV records for .DE and .FR IRIS DCHK service
        requires:
            IO::Compress::RawDeflate:  0
            IO::Uncompress::RawInflate:  0
            Net::DNS:             0
    webservices:
        description:  Support of webservices for the following registry drivers: Gandi, BookMyName, OVH
        requires:
            SOAP::Lite:    0
            SOAP::WSDL:    0
            XMLRPC::Lite:  0
