# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-DRI
version:      0.30
version_from: lib/Net/DRI.pm
installdirs:  site
requires:
    Class::Accessor:               0
    Class::Accessor::Chained:      0
    DateTime:                      0
    DateTime::Duration:            0
    DateTime::Format::ISO8601:     0
    DateTime::Format::Strptime:    0
    DateTime::TimeZone:            0
    Email::Valid:                  0
    IO::Socket::INET:              0
    IO::Socket::SSL:               0.90
    MIME::Entity:                  0
    Net::SMTP:                     0
    SOAP::Lite:                    0
    Test::More:                    0
    Time::HiRes:                   0
    WWW::Mechanize:                0
    XML::LibXML:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
