--- #YAML:1.0
name:                Net-DRI
version:             0.91
abstract:            Interface to Domain Name Registries/Registrars/Resellers
license:             gpl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Carp:                          0
    Class::Accessor:               0
    Class::Accessor::Chained:      0
    DateTime:                      0
    DateTime::Duration:            0
    DateTime::Format::ISO8601:     0.06
    DateTime::Format::Strptime:    0
    DateTime::TimeZone:            0
    Email::Valid:                  0
    IO::Socket::INET:              0
    IO::Socket::SSL:               0.90
    Test::More:                    0
    Time::HiRes:                   0
    UNIVERSAL::require:            0
    XML::LibXML:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Patrick Mevzek <netdri@dotandco.com>
